# Generated by Django 4.2.1 on 2023-08-08 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cupon_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
