# Generated by Django 4.2.1 on 2023-08-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='is_sub',
            field=models.BooleanField(default=True),
        ),
    ]
